### ISSUE TITLE
Willing to help compile for the Mac

### ISSUE THREAD

**Issue by titaniumjones** [hojonathanho/bulletsim#2]
Hi,
I'm no expert, but I have a keen interest in helping support you develop on the mac.
I have followed the linux compile instructions you posted and get 99% the way through. The first error I encountered was:
-soname not supported or something..... 
I tracked this down to a Mac specific issue. the mac equivalent is:
 -install_name
which I replaced in the makefile. 
I now have the error:
ld: symbol(s) not found for architecture x86_64
but I'm stumped on how to fix this. Any guidance or discussion would be greatly appreciated.

**Comment by joschu** [comment]
Hi titaniumjones, are you sure you're in the right place? We didn't post any compilation instructions.

**Comment by titaniumjones** [comment]
Well I'm not sure, now, where I got the compilation instructions from, but I definitely read it somewhere. Hmmmm I'll have a hunt around and see what I can find.
